### ISSUE TITLE
Name of the docker containers 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron-docker-stack#4]
Currently all the Docker container names end with `-image` is this necessary? 
https://hub.docker.com/u/muhhassani

I would prefer something like: 
`pyiron/pyiron `
or even: 
`pyiron/atomistic`, `pyiron/base` and so on

**Comment by muh-hassani** [comment]
I wanted to make the image distinguish from the package itself. But it is not necessary. Therefore, we can change them, e.g. pyiron/pyiron instead of pyiron/pyiron-image
